# Generated by Django 4.2.7 on 2026-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_voicecallrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deepseek_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='DeepSeek API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doubao_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='豆包API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='Gemini API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kimi_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='Kimi API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='OpenAI API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qwen_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='通义千问API密钥'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qwen_code_api_key',
            field=models.TextField(blank=True, null=True, verbose_name='通义千问代码API密钥'),
        ),
    ]
