# Generated by Django 4.2.7 on 2026-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='使用的模型'),
        ),
    ]
