# Generated by Django 4.2.7 on 2026-01-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('text', '文字聊天'), ('voice', '语音通话'), ('video', '视频通话')], default='text', max_length=10, verbose_name='聊天模式'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='语音时长(秒)'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/', verbose_name='语音文件'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('video', '视频消息')], default='text', max_length=10, verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='message',
            name='transcription_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='语音识别置信度'),
        ),
    ]
