# Generated by Django 4.2.7 on 2026-01-26 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='通话ID')),
                ('status', models.CharField(choices=[('pending', '等待接听'), ('accepted', '已接听'), ('rejected', '已拒绝'), ('ended', '已结束'), ('missed', '未接听')], default='pending', max_length=20, verbose_name='通话状态')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接听时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='通话时长(秒)')),
                ('caller_device_info', models.JSONField(blank=True, null=True, verbose_name='主叫设备信息')),
                ('callee_device_info', models.JSONField(blank=True, null=True, verbose_name='被叫设备信息')),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL, verbose_name='被叫用户')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL, verbose_name='主叫用户')),
            ],
            options={
                'verbose_name': '语音通话记录',
                'verbose_name_plural': '语音通话记录',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
