# Generated by Django 4.2.7 on 2026-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_userprofile_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('text', '文字聊天'), ('voice', '语音通话'), ('video', '视频通话')], db_index=True, default='text', max_length=10, verbose_name='聊天模式'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(db_index=True, default='gpt-3.5-turbo', max_length=50, verbose_name='使用的模型'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='会话标题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('video', '视频消息')], db_index=True, default='text', max_length=10, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('assistant', '助手')], db_index=True, max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='接听时间'),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='call_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='通话ID'),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发起时间'),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待接听'), ('accepted', '已接听'), ('rejected', '已拒绝'), ('ended', '已结束'), ('missed', '未接听')], db_index=True, default='pending', max_length=20, verbose_name='通话状态'),
        ),
    ]
