# Generated by Django 4.2.7 on 2026-01-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/person.jpg', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
