# Generated by Django 4.2.7 on 2026-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_analytics',
            field=models.BooleanField(default=True, verbose_name='允许数据统计'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='zh-CN', max_length=10, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='save_chat_history',
            field=models.BooleanField(default=True, verbose_name='保存聊天记录'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='auto', max_length=20, verbose_name='主题模式'),
        ),
    ]
